NUMPY FUNDAMENTALS 

In [29]:
import numpy as np 

arr1= np.array({1,2,3,4,5})
print (arr1)
print(type(arr1))
print(arr1.shape)

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>
()


In [30]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:

# 2D array
arr3 = np.array([[1,2,3,4] , [5,6,7,8]])
print(arr3.shape)

(2, 4)


In [32]:
# crate araay using the inbuilt functions
# arange(start , stop , step)

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [33]:
# create arrays of reqiured size of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# for identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# ## attribute sof numpy array

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n" ,arr)
print("Shape :" , arr.shape)
print("Number of dimensions:" , arr.ndim)
print("No of ele " , arr.size)
print("data type", arr.dtype)
print("Item size (in bytes)" , arr.itemsize )

Array:
 [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Number of dimensions: 2
No of ele  6
data type int64
Item size (in bytes) 8


In [36]:
# ## numpy vectorised operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition

print("addition" , arr1+arr2)

# elementwise substraction
print("subtraction" , arr1-arr2)

# multiplication
print("multiplication" , arr1*arr2)

addition [11 22 33 44 55]
subtraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]


In [37]:
# universal functions

arr = np.array([2,3,4,5,6])

## squareroot

print(np.sqrt(arr))
print(np.exp(arr))


#similarly sin ,log ..

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [38]:
# 1D array
a = np.array([10, 20, 30, 40, 50])

# 2D array
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a[0]      # first element
a[-1]     # last element
a[2]      # element at index 2
a[1:4]    # elements from index 1 to 3
a[:3]     # first 3 elements
a[2:]     # from index 2 to end
a[::2]    # step = 2
a[::-1]   # reverse array


b[0, 1]   # element at row 0, column 1
b[1]      # second row
b[:, 0]   # first column


array([1, 4, 7])

In [39]:
data = np.array([1, 2, 2, 3, 4, 5])
x =data
np.mean(data)
np.median(data)
np.var(data)
np.std(data)

np.mean(x)     # mean
np.median(x)   # median
np.var(x)      # variance
np.std(x)      # standard deviation


np.float64(1.3437096247164249)

In [40]:
data = np.array([1, 2, 2, 3, 4, 5])
print(data>3)

print(data[data>3])

[False False False False  True  True]
[4 5]


## PANDAS

In [41]:
import pandas as pd

df = pd.read_csv('example.csv')

df.head(2) #Shows first n rows (5 rows by default)
df.tail(2) #similarly last 

# df.rename() 

,ID,Name,Age,Marks,City
3,4,David,22,88,Berlin
4,5,Eva,20,90,Rome


In [42]:
df.describe()
# give statitistical data such as mean median std etc

,ID,Age,Marks
count,5.000000,5.000000,5.000000
mean,3.000000,20.400000,86.600000
std,1.581139,1.140175,5.458938
min,1.000000,19.000000,78.000000
25%,2.000000,20.000000,85.000000
50%,3.000000,20.000000,88.000000
75%,4.000000,21.000000,90.000000
max,5.000000,22.000000,92.000000


handling missing values

In [43]:
df1 = pd.read_csv('missing.csv')
#to check how many are missing 
df1.isnull().sum()

##filling missing values with any number 
filled = df1.fillna(0)
filled




,ID,Name,Age,Marks,City
0,1,Alice,20.0,85.0,New York
1,2,Bob,0.0,78.0,London
2,3,Charlie,19.0,0.0,Paris
3,4,David,22.0,88.0,0
4,5,Eva,0.0,90.0,Rome


In [44]:
#filling missing values with mean 

df['age_fillNa'] = df1['Age'].fillna(df1['Age'].mean())
df

,ID,Name,Age,Marks,City,age_fillNa
0,1,Alice,20,85,New York,20.000000
1,2,Bob,21,78,London,20.333333
2,3,Charlie,19,92,Paris,19.000000
3,4,David,22,88,Berlin,22.000000
4,5,Eva,20,90,Rome,20.333333


In [45]:
#reanming columns 

df = df.rename(columns={'Age' : 'Curr Age'})
df

,ID,Name,Curr Age,Marks,City,age_fillNa
0,1,Alice,20,85,New York,20.000000
1,2,Bob,21,78,London,20.333333
2,3,Charlie,19,92,Paris,19.000000
3,4,David,22,88,Berlin,22.000000
4,5,Eva,20,90,Rome,20.333333


In [46]:
#manipulation operations 

df['Age+10'] = df['Curr Age'].apply(lambda x : x+10)
df

,ID,Name,Curr Age,Marks,City,age_fillNa,Age+10
0,1,Alice,20,85,New York,20.000000,30
1,2,Bob,21,78,London,20.333333,31
2,3,Charlie,19,92,Paris,19.000000,29
3,4,David,22,88,Berlin,22.000000,32
4,5,Eva,20,90,Rome,20.333333,30


In [47]:
## data aggeragating and grouping 

# group_mean = df.groupby('Marks')['']

# merging and joining dataframes



## merging and joining data frames 

In [48]:
df1 = pd.DataFrame({'key': ['a' , 'b' , 'c'] , 'value1':[1,2,3]})
df2 = pd.DataFrame({'key':['a','b','d'] , 'value2':[4,5,6]})

In [49]:
df1

,key,value1
0,a,1
1,b,2
2,c,3


In [50]:
df2

,key,value2
0,a,4
1,b,5
2,d,6


In [51]:
pd.merge(df1 , df2 , on='key', how='inner')

,key,value1,value2
0,a,1,4
1,b,2,5


In [52]:
pd.merge(df1 , df2 , on='key', how='outer')

,key,value1,value2
0,a,1.0,4.0
1,b,2.0,5.0
2,c,3.0,NaN
3,d,NaN,6.0


#data agreegating and  groupping 

In [61]:
df.head
grouped_mean= df.groupby('Curr Age')['ID'].mean()
print(grouped_mean)

Curr Age
19    3.0
20    3.0
21    2.0
22    4.0
Name: ID, dtype: float64
